In [1]:
import tensorflow as tf

### Tensor 정의 방법 1

In [2]:
# compat.v1 : Tensorflow 2에서 1코드 사용
# disable_eager_execution() : session.run() 으로 실행하기 위해
tf.compat.v1.disable_eager_execution()

In [3]:
# 텐서 정의 (상수/변수)
x = tf.constant(1, name='x')
y = tf.Variable(x+9,name='y')

In [4]:
# 코드가 실행(run/eval)되면 값이 정의
print(x)

Tensor("x:0", shape=(), dtype=int32)


In [5]:
print(y)

<tf.Variable 'y:0' shape=() dtype=int32>


In [6]:
# global_variables_initializer(): 텐서 초기화, run() 해야 초기화 됨
model = tf.compat.v1.global_variables_initializer() 

In [7]:
with tf.compat.v1.Session() as session:
    session.run(model)
    print(session.run(y))

10


### Tensor 정의 방법 2

In [8]:
tf.compat.v1.disable_eager_execution()

In [9]:
# placeholder(데이터타입) : 텐서를 정의
a = tf.compat.v1.placeholder("int32") 
b = tf.compat.v1.placeholder("int32")

y = tf.multiply(a,b)

sess = tf.compat.v1.Session()

In [10]:
print(sess.run(y, feed_dict={a:2,b:5}))

10


### Tensor 정의 방법 3

In [11]:
import numpy as np

In [12]:
tensor_2d=np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])

print(tensor_2d)
print(tensor_2d[3][3])
print(tensor_2d[0:2,0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
15
[[1 2]
 [4 5]]


In [13]:
tf.compat.v1.disable_eager_execution()

# convert_to_tensor() : numpy 행렬을 tensorflow 행렬로 변환
tf_tensor = tf.convert_to_tensor(tensor_2d, dtype=tf.float64)
with tf.compat.v1.Session() as sess:
    print(sess.run(tf_tensor))

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
